# Generated by Django 4.2.7 on 2026-05-13 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_hi', models.CharField(max_length=200)),
                ('name_pa', models.CharField(blank=True, max_length=200)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
                ('eligibility', models.TextField()),
                ('application_process', models.TextField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('website', models.URLField()),
                ('icon', models.CharField(default='📜', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchemeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('document_required', 'More Documents Required')], default='pending', max_length=20)),
                ('application_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_applications', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='schemes.governmentscheme')),
            ],
        ),
    ]
