# Generated by Django 4.2.11 on 2026-05-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='governmentscheme',
            old_name='name_pa',
            new_name='financial_assistance',
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='category',
            field=models.CharField(choices=[('income_support', 'Income Support'), ('insurance', 'Crop Insurance'), ('credit_loan', 'Credit & Loan'), ('infrastructure', 'Infrastructure'), ('mechanization', 'Farm Mechanization'), ('irrigation', 'Irrigation'), ('organic_farming', 'Organic Farming'), ('horticulture', 'Horticulture'), ('seed_planting', 'Seed & Planting'), ('marketing', 'Marketing'), ('digital_agri', 'Digital Agriculture'), ('pension', 'Pension & Welfare')], default='income_support', max_length=50),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='documents_required',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='name_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
