# Generated by Django 4.2.7 on 2026-05-13 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_hi', models.CharField(blank=True, max_length=50)),
                ('name_pa', models.CharField(blank=True, max_length=50)),
                ('scientific_name', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(choices=[('kharif', 'Kharif (June-October)'), ('rabi', 'Rabi (October-March)'), ('zaid', 'Zaid (March-June)')], max_length=10)),
                ('sowing_period', models.CharField(max_length=100)),
                ('harvesting_period', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in acres', max_digits=10)),
                ('sowing_date', models.DateField()),
                ('expected_harvest', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CropAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_stage', models.CharField(choices=[('sowing', 'Sowing'), ('germination', 'Germination'), ('vegetative', 'Vegetative Growth'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting'), ('harvesting', 'Harvesting')], max_length=20)),
                ('weather_condition', models.CharField(default='normal', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('advice', models.TextField()),
                ('advice_hi', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=1)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisories', to='crops.crop')),
            ],
            options={
                'ordering': ['priority', 'growth_stage'],
            },
        ),
    ]
