# Generated by Django 4.2.7 on 2026-05-13 10:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_from_farmer',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='is_available',
        ),
        migrations.AddField(
            model_name='buyer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_type',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer')], default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productlisting',
            name='harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='quality',
            field=models.CharField(choices=[('Premium', 'Premium Quality'), ('Standard', 'Standard Quality'), ('Fair', 'Fair Quality')], default='Standard', max_length=50),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending Sale'), ('sold', 'Sold'), ('expired', 'Expired')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('negotiating', 'Negotiating')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.buyer')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='chat.productlisting')),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='interest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.interest'),
            preserve_default=False,
        ),
    ]
